local highlights = {
		Normal = {fg = C.fg, bg = Config.transparent_background and "NONE" or C.bg, },
		SignColumn = {bg = C.bg, },
		MsgArea = {fg = C.fg, bg = Config.transparent_background and "NONE" or C.bg, },
		ModeMsg = {fg = C.fg, bg = C.bg, },
		MsgSeparator = {fg = C.fg, bg = C.bg, },
		SpellBad = {fg = C.error_red, style = "underline", },
		SpellCap = {fg = C.yellow, style = "underline", },
		SpellLocal = {fg = C.green, style = "underline", },
		SpellRare = {fg = C.purple, style = "underline", },
		NormalNC = {fg = C.fg, bg = Config.transparent_background and "NONE" or C.bg, },
		Pmenu = {fg = C.light_gray, bg = C.popup_back, },
		PmenuSel = {fg = C.alt_bg, bg = C.blue, },
		WildMenu = {fg = C.alt_bg, bg = C.blue, },
		CursorLineNr = {fg = C.light_gray, style = "NONE", },
		-- Comment = {fg = C.context, style = "italic", },
		Comment = {fg = C.gray, style = "italic", },
		Folded = {fg = C.accent, bg = C.alt_bg, },
		FoldColumn = {fg = C.accent, bg = C.alt_bg, },
		LineNr = {fg = C.context, },
		FloatBoder = {fg = C.gray, bg = C.alt_bg, },
		Whitespace = {fg = C.bg, },
		VertSplit = {fg = C.bg, bg = C.fg, },
		CursorLine = {bg = C.dark, },
		CursorColumn = {bg = C.dark, },
		ColorColumn = {bg = C.dark, },
		NormalFloat = {bg = C.bg, },
		Visual = {bg = C.visual_grey, },
		VisualNOS = {bg = C.alt_bg, },
		WarningMsg = {fg = C.error_red, bg = C.bg, },
		DiffAdd = {fg = C.alt_bg, bg = C.sign_add, },
		DiffChange = {fg = C.alt_bg, bg = C.sign_change, style = "underline", },
		DiffDelete = {fg = C.alt_bg, bg = C.sign_delete, },
		QuickFixLine = {bg = C.dark_gray, },
		PmenuSbar = {bg = C.alt_bg, },
		PmenuThumb = {bg = C.gray, },
		MatchWord = {style = "underline", },
		MatchParen = {fg = C.hint_blue, bg = C.bg, style = "underline", },
		MatchWordCur = {style = "underline", },
		MatchParenCur = {style = "underline", },
		Cursor = {fg = C.cursor_fg, bg = C.cursor_bg, },
		lCursor = {fg = C.cursor_fg, bg = C.cursor_bg, },
		CursorIM = {fg = C.cursor_fg, bg = C.cursor_bg, },
		TermCursor = {fg = C.cursor_fg, bg = C.cursor_bg, },
		TermCursorNC = {fg = C.cursor_fg, bg = C.cursor_bg, },
		Conceal = {fg = C.accent, },
		Directory = {fg = C.blue, },
		SpecialKey = {fg = C.blue, style = "NONE", },
		Title = {fg = C.blue, style = "NONE", },
		ErrorMsg = {fg = C.error_red, bg = C.bg, style = "NONE", },
		Search = {fg = C.bg, bg = C.search_orange, },
		IncSearch = {fg = C.search_orange, bg = C.bg, },
		Substitute = {fg = C.bg, bg = C.search_orange, },
		MoreMsg = {fg = C.orange, },
		Question = {fg = C.orange, },
		EndOfBuffer = {fg = C.bg, },
		NonText = {fg = C.context, style = "NONE",},
		Variable = {fg = C.cyan, style = "NONE",},
		String = {fg = C.green, style = "NONE",},
		Character = {fg = C.green, style = "NONE",},
		Constant = {fg = C.orange, style = "NONE",},
		Number = {fg = C.orange, style = "NONE",},
		Boolean = {fg = C.orange, style = "NONE",},
		Float = {fg = C.orange, style = "NONE",},
		Identifier = {fg = C.fg, style = "NONE",},
		Function = {fg = C.blue, style = "NONE",},
		Operator = {fg = C.purple, style = "NONE",},
		Type = {fg = C.yellow, style = "NONE",},
		StorageClass = {fg = C.cyan, style = "NONE",},
		Structure = {fg = C.purple, style = "NONE",},
		Typedef = {fg = C.purple, style = "NONE",},
		Keyword = {fg = C.purple, style = "NONE",},
		Statement = {fg = C.purple, style = "NONE",},
		Conditional = {fg = C.purple, style = "NONE",},
		Repeat = {fg = C.purple, style = "NONE",},
		Label = {fg = C.blue, style = "NONE",},
		Exception = {fg = C.purple, style = "NONE",},
		Include = {fg = C.purple, style = "NONE",},
		PreProc = {fg = C.purple, style = "NONE",},
		Define = {fg = C.purple, style = "NONE",},
		Macro = {fg = C.purple, style = "NONE",},
		PreCondit = {fg = C.purple, style = "NONE",},
		Special = {fg = C.purple, style = "NONE",},
		SpecialChar = {fg = C.fg, style = "NONE",},
		Tag = {fg = C.blue, style = "NONE",},
		Debug = {fg = C.red, },
		Delimiter = {fg = C.fg, },
		SpecialComment = {fg = C.gray, style = "NONE",},
		Underlined = {style = "underline", },
		Bold = {style = "bold", },
		Italic = {style = "italic", },
		Ignore = {fg = C.cyan, bg = C.bg, style = "NONE", },
		Todo = {fg = C.red, bg = C.bg, style = "NONE", },
		Error = {fg = C.error_red, bg = C.bg, style = "NONE", },

		-- TabLine = {fg = C.light_gray, bg = C.alt_bg, },
		-- TabLineSel = {fg = C.fg, bg = C.alt_bg, },
		-- TabLineFill = {fg = C.fg, bg = C.alt_bg, },

		TabLine        = {fg = C.fg, bg = C.dark, },
		TabLineSel     = {fg = C.bg, bg = C.green, },
		TabLineFill    = {fg = C.bg, bg = C.green, },
		TabLineMod     = {fg = C.info_yellow, bg = C.dark, },
		TabLineModSel  = {fg = C.bg, bg = C.yellow_orange, },
		TabLineDiag    = {fg = C.red, bg = C.dark, },
		TabLineDiagSel = {fg = C.bg, bg = C.green, },
		TabLineDiagModSel = {fg = C.bg, bg = C.yellow_orange, },

-- 		TabLine        = {fg = C.fg, bg = C.dark, },
-- 		TabLineSel     = {fg = C.black, bg = C.green, },
-- 		TabLineFill    = {fg = C.black, bg = C.green, },
-- 		TabLineMod     = {fg = C.info_yellow, bg = C.dark, },
-- 		TabLineModSel  = {fg = C.black, bg = C.yellow_orange, },
-- 		TabLineDiag    = {fg = C.red, bg = C.dark, },
-- 		TabLineDiagSel = {fg = C.black, bg = C.green, },
-- 		TabLineDiagModSel = {fg = C.black, bg = C.yellow_orange, },

}

return highlights
